### PR TITLE
Main

### PR DESCRIPTION
**Pull request by yosef406**

### CODE REVIEW

**Comment by yosef406** [comment]
please don't make problems, be nice 😅

**Comment by HosenNaser** [comment]
I like your todo tasks list but it's not enough for one day of work !!
you guys have to work harder 😁

**Review by FidaKhoury — APPROVED** [review]
I recommend to add the changes on readme each time you commit a change, so it doesn't be a last minute job 👍 
its only a recommendation not necessary :)

**Comment by FidaKhoury** [comment]
we will try to be nice 😁 for now good job guys 👍

**Pull request merged**
