### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by reemaRahhal**
We updated an initial README file during build the project ,  it will be updated accordingly

### CODE REVIEW

**Review by HosenNaser — APPROVED** [review]
good job

**Comment by HosenNaser** [comment]
@reemaRahhal 
you are not allowed to close any pull request without my team permissions the next time..

**Comment by reemaRahhal** [comment]
@HosenNaser  
Sorry, I closed pull request  by mistake 
I already did reopen pull request

**Comment by HosenNaser** [comment]
I'm sorry if it was rude in this point, but please next time wait for our approve and if we late just ask for it in a comment thanks @reemaRahhal

**Pull request merged**
